spring:
  datasource:
    url: jdbc:h2:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: default
    hibernate:
      ddl-auto: create-drop
    show-sql: true
