spring:
  datasource:
    url: jdbc:h2:./src/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
